import { getSymbolForWord } from './symbols';

export interface DefaultWord {
  label: string;
  speak: string;
  color: string;
  category: string;
  usage_count: number;
  symbol: string;
}

export interface DefaultCategory {
  name: string;
  color: string;
}

const COLOR_SEMANTICS = {
  core: '#1565C0',
  family: '#2E7D32',
  action: '#00897B',
  object: '#EF6C00',
  feeling: '#8E24AA',
  urgent: '#C62828',
  question: '#F9A825',
};

export const CORE_WORD_LABELS = ['I', 'Want', 'Need', 'More', 'Help', 'Stop', 'Go', 'Yes', 'No', 'Like', 'Not', 'Eat'];

export const DEFAULT_CATEGORIES: DefaultCategory[] = [
  { name: 'Core Words', color: COLOR_SEMANTICS.core },
  { name: 'People', color: '#AD1457' },
  { name: 'Food & Drink', color: '#F57C00' },
  { name: 'Activities', color: COLOR_SEMANTICS.action },
  { name: 'Home', color: COLOR_SEMANTICS.family },
  { name: 'School', color: '#3949AB' },
  { name: 'Places', color: COLOR_SEMANTICS.object },
  { name: 'Feelings', color: COLOR_SEMANTICS.feeling },
  { name: 'Actions', color: '#D81B60' },
  { name: 'Descriptors', color: '#00897B' },
  { name: 'Time', color: '#00838F' },
  { name: 'Questions', color: COLOR_SEMANTICS.question },
];

export const LEGACY_DEFAULT_SPEAK_BY_LABEL: Record<string, string> = {
  Want: 'I want',
  Need: 'I need',
  Like: 'I like',
  Help: 'Please help me',
  Eat: 'I want to eat',
  Drink: 'I want a drink',
  'All done': 'I am all done',
  Play: 'I want to play',
  Bathroom: 'I need the bathroom',
  Exercise: 'I want to do exercises',
  Tired: 'I am tired',
  Pain: 'It hurts',
  Car: 'I want to go in the car',
  Park: 'I want to go to the park',
  Store: 'I want to go to the store',
  Home: 'I want to go home',
  Outside: 'I want to go outside',
  Happy: 'I feel happy',
  Sad: 'I feel sad',
  Angry: 'I feel angry',
  Scared: 'I feel scared',
  Sick: 'I feel sick',
  Come: 'Come here',
};

const BASE_WORDS = [
  // Core Words - fundamental for all communication
  { label: 'I', speak: 'I', color: COLOR_SEMANTICS.core, category: 'Core Words' },
  { label: 'You', speak: 'You', color: COLOR_SEMANTICS.core, category: 'Core Words' },
  { label: 'We', speak: 'We', color: COLOR_SEMANTICS.core, category: 'Core Words' },
  { label: 'He', speak: 'He', color: COLOR_SEMANTICS.core, category: 'Core Words' },
  { label: 'She', speak: 'She', color: COLOR_SEMANTICS.core, category: 'Core Words' },
  { label: 'Want', speak: 'Want', color: COLOR_SEMANTICS.core, category: 'Core Words' },
  { label: 'Need', speak: 'Need', color: COLOR_SEMANTICS.core, category: 'Core Words' },
  { label: 'Like', speak: 'Like', color: COLOR_SEMANTICS.core, category: 'Core Words' },
  { label: 'Love', speak: 'Love', color: COLOR_SEMANTICS.core, category: 'Core Words' },
  { label: 'Don\'t like', speak: 'Don\'t like', color: COLOR_SEMANTICS.core, category: 'Core Words' },
  { label: 'Not', speak: 'Not', color: COLOR_SEMANTICS.core, category: 'Core Words' },
  { label: 'Can', speak: 'Can', color: COLOR_SEMANTICS.core, category: 'Core Words' },
  { label: 'Can\'t', speak: 'Can\'t', color: COLOR_SEMANTICS.core, category: 'Core Words' },
  { label: 'More', speak: 'More', color: COLOR_SEMANTICS.core, category: 'Core Words' },
  { label: 'All done', speak: 'All done', color: COLOR_SEMANTICS.core, category: 'Core Words' },
  { label: 'Help', speak: 'Help', color: COLOR_SEMANTICS.urgent, category: 'Core Words' },
  { label: 'Yes', speak: 'Yes', color: COLOR_SEMANTICS.question, category: 'Core Words' },
  { label: 'No', speak: 'No', color: COLOR_SEMANTICS.urgent, category: 'Core Words' },
  { label: 'This', speak: 'This', color: COLOR_SEMANTICS.core, category: 'Core Words' },
  { label: 'That', speak: 'That', color: COLOR_SEMANTICS.core, category: 'Core Words' },
  { label: 'Mine', speak: 'Mine', color: COLOR_SEMANTICS.core, category: 'Core Words' },
  { label: 'Have', speak: 'Have', color: COLOR_SEMANTICS.core, category: 'Core Words' },
  { label: 'Okay', speak: 'Okay', color: COLOR_SEMANTICS.core, category: 'Core Words' },
  { label: 'Please', speak: 'Please', color: COLOR_SEMANTICS.core, category: 'Core Words' },
  { label: 'Thank you', speak: 'Thank you', color: COLOR_SEMANTICS.core, category: 'Core Words' },

  // People and Relationships
  { label: 'Mom', speak: 'Mom', color: '#AD1457', category: 'People' },
  { label: 'Dad', speak: 'Dad', color: '#AD1457', category: 'People' },
  { label: 'Mama', speak: 'Mama', color: '#AD1457', category: 'People' },
  { label: 'Dada', speak: 'Dada', color: '#AD1457', category: 'People' },
  { label: 'Sister', speak: 'Sister', color: '#AD1457', category: 'People' },
  { label: 'Brother', speak: 'Brother', color: '#AD1457', category: 'People' },
  { label: 'Grandma', speak: 'Grandma', color: '#AD1457', category: 'People' },
  { label: 'Grandpa', speak: 'Grandpa', color: '#AD1457', category: 'People' },
  { label: 'Cousin', speak: 'Cousin', color: '#AD1457', category: 'People' },
  { label: 'Aunt', speak: 'Aunt', color: '#AD1457', category: 'People' },
  { label: 'Uncle', speak: 'Uncle', color: '#AD1457', category: 'People' },
  { label: 'Teacher', speak: 'Teacher', color: '#AD1457', category: 'People' },
  { label: 'Therapist', speak: 'Therapist', color: '#AD1457', category: 'People' },
  { label: 'Friend', speak: 'Friend', color: '#AD1457', category: 'People' },
  { label: 'Friends', speak: 'Friends', color: '#AD1457', category: 'People' },
  { label: 'Baby', speak: 'Baby', color: '#AD1457', category: 'People' },
  { label: 'Pet', speak: 'Pet', color: '#AD1457', category: 'People' },
  { label: 'Dog', speak: 'Dog', color: '#AD1457', category: 'People' },
  { label: 'Cat', speak: 'Cat', color: '#AD1457', category: 'People' },
  { label: 'Person', speak: 'Person', color: '#AD1457', category: 'People' },

  // Food & Drink
  { label: 'Eat', speak: 'Eat', color: '#F57C00', category: 'Food & Drink' },
  { label: 'Drink', speak: 'Drink', color: '#F57C00', category: 'Food & Drink' },
  { label: 'Water', speak: 'Water', color: '#F57C00', category: 'Food & Drink' },
  { label: 'Milk', speak: 'Milk', color: '#F57C00', category: 'Food & Drink' },
  { label: 'Juice', speak: 'Juice', color: '#F57C00', category: 'Food & Drink' },
  { label: 'Apple', speak: 'Apple', color: '#F57C00', category: 'Food & Drink' },
  { label: 'Orange', speak: 'Orange', color: '#F57C00', category: 'Food & Drink' },
  { label: 'Banana', speak: 'Banana', color: '#F57C00', category: 'Food & Drink' },
  { label: 'Bread', speak: 'Bread', color: '#F57C00', category: 'Food & Drink' },
  { label: 'Cheese', speak: 'Cheese', color: '#F57C00', category: 'Food & Drink' },
  { label: 'Cookie', speak: 'Cookie', color: '#F57C00', category: 'Food & Drink' },
  { label: 'Crackers', speak: 'Crackers', color: '#F57C00', category: 'Food & Drink' },
  { label: 'Pizza', speak: 'Pizza', color: '#F57C00', category: 'Food & Drink' },
  { label: 'Snack', speak: 'Snack', color: '#F57C00', category: 'Food & Drink' },
  { label: 'Hungry', speak: 'Hungry', color: '#F57C00', category: 'Food & Drink' },
  { label: 'Thirsty', speak: 'Thirsty', color: '#F57C00', category: 'Food & Drink' },
  { label: 'Hot', speak: 'Hot', color: '#F57C00', category: 'Food & Drink' },
  { label: 'Cold', speak: 'Cold', color: '#F57C00', category: 'Food & Drink' },
  { label: 'Yummy', speak: 'Yummy', color: '#F57C00', category: 'Food & Drink' },
  { label: 'Gross', speak: 'Gross', color: '#F57C00', category: 'Food & Drink' },

  // Time
  { label: 'Now', speak: 'Now', color: '#00838F', category: 'Time' },
  { label: 'Later', speak: 'Later', color: '#00838F', category: 'Time' },
  { label: 'After', speak: 'After', color: '#00838F', category: 'Time' },
  { label: 'Before', speak: 'Before', color: '#00838F', category: 'Time' },
  { label: 'Morning', speak: 'Morning', color: '#00838F', category: 'Time' },
  { label: 'Afternoon', speak: 'Afternoon', color: '#00838F', category: 'Time' },
  { label: 'Night', speak: 'Night', color: '#00838F', category: 'Time' },
  { label: 'Today', speak: 'Today', color: '#00838F', category: 'Time' },
  { label: 'Tomorrow', speak: 'Tomorrow', color: '#00838F', category: 'Time' },
  { label: 'Yesterday', speak: 'Yesterday', color: '#00838F', category: 'Time' },
  { label: 'Monday', speak: 'Monday', color: '#00838F', category: 'Time' },
  { label: 'Friday', speak: 'Friday', color: '#00838F', category: 'Time' },
  { label: 'Weekend', speak: 'Weekend', color: '#00838F', category: 'Time' },
  { label: 'Wait', speak: 'Wait', color: '#00838F', category: 'Time' },
  { label: 'Soon', speak: 'Soon', color: '#00838F', category: 'Time' },

  // Questions
  { label: 'What', speak: 'What', color: COLOR_SEMANTICS.question, category: 'Questions' },
  { label: 'Where', speak: 'Where', color: COLOR_SEMANTICS.question, category: 'Questions' },
  { label: 'When', speak: 'When', color: COLOR_SEMANTICS.question, category: 'Questions' },
  { label: 'Why', speak: 'Why', color: COLOR_SEMANTICS.question, category: 'Questions' },
  { label: 'Who', speak: 'Who', color: COLOR_SEMANTICS.question, category: 'Questions' },
  { label: 'How', speak: 'How', color: COLOR_SEMANTICS.question, category: 'Questions' },
  { label: 'Which', speak: 'Which', color: COLOR_SEMANTICS.question, category: 'Questions' },
  { label: 'Do you', speak: 'Do you', color: COLOR_SEMANTICS.question, category: 'Questions' },
  { label: 'Can I', speak: 'Can I', color: COLOR_SEMANTICS.question, category: 'Questions' },
  { label: 'Is it', speak: 'Is it', color: COLOR_SEMANTICS.question, category: 'Questions' },

  // Home + daily activities
  { label: 'Home', speak: 'Home', color: COLOR_SEMANTICS.family, category: 'Home' },
  { label: 'Bed', speak: 'Bed', color: COLOR_SEMANTICS.family, category: 'Home' },
  { label: 'Sleep', speak: 'Sleep', color: COLOR_SEMANTICS.family, category: 'Home' },
  { label: 'Wake up', speak: 'Wake up', color: COLOR_SEMANTICS.family, category: 'Home' },
  { label: 'Bath', speak: 'Bath', color: COLOR_SEMANTICS.family, category: 'Home' },
  { label: 'Wash', speak: 'Wash', color: COLOR_SEMANTICS.family, category: 'Home' },
  { label: 'Brush teeth', speak: 'Brush teeth', color: COLOR_SEMANTICS.family, category: 'Home' },
  { label: 'Bathroom', speak: 'Bathroom', color: COLOR_SEMANTICS.family, category: 'Home' },
  { label: 'Potty', speak: 'Potty', color: COLOR_SEMANTICS.family, category: 'Home' },
  { label: 'TV', speak: 'TV', color: COLOR_SEMANTICS.family, category: 'Home' },
  { label: 'Movie', speak: 'Movie', color: COLOR_SEMANTICS.family, category: 'Home' },
  { label: 'Show', speak: 'Show', color: COLOR_SEMANTICS.family, category: 'Home' },
  { label: 'Music', speak: 'Music', color: COLOR_SEMANTICS.family, category: 'Home' },
  { label: 'Song', speak: 'Song', color: COLOR_SEMANTICS.family, category: 'Home' },
  { label: 'Sing', speak: 'Sing', color: COLOR_SEMANTICS.family, category: 'Home' },
  { label: 'Dance', speak: 'Dance', color: COLOR_SEMANTICS.family, category: 'Home' },
  { label: 'Play', speak: 'Play', color: COLOR_SEMANTICS.family, category: 'Home' },
  { label: 'Toy', speak: 'Toy', color: COLOR_SEMANTICS.family, category: 'Home' },
  { label: 'Game', speak: 'Game', color: COLOR_SEMANTICS.family, category: 'Home' },
  { label: 'Blanket', speak: 'Blanket', color: COLOR_SEMANTICS.family, category: 'Home' },
  { label: 'Hug', speak: 'Hug', color: COLOR_SEMANTICS.family, category: 'Home' },
  { label: 'Kiss', speak: 'Kiss', color: COLOR_SEMANTICS.family, category: 'Home' },

  // School
  { label: 'School', speak: 'School', color: '#3949AB', category: 'School' },
  { label: 'Book', speak: 'Book', color: '#3949AB', category: 'School' },
  { label: 'Read', speak: 'Read', color: '#3949AB', category: 'School' },
  { label: 'Write', speak: 'Write', color: '#3949AB', category: 'School' },
  { label: 'Draw', speak: 'Draw', color: '#3949AB', category: 'School' },
  { label: 'Draw', speak: 'Draw', color: '#3949AB', category: 'School' },
  { label: 'Pencil', speak: 'Pencil', color: '#3949AB', category: 'School' },
  { label: 'Pen', speak: 'Pen', color: '#3949AB', category: 'School' },
  { label: 'Paper', speak: 'Paper', color: '#3949AB', category: 'School' },
  { label: 'Marker', speak: 'Marker', color: '#3949AB', category: 'School' },
  { label: 'Color', speak: 'Color', color: '#3949AB', category: 'School' },
  { label: 'Cut', speak: 'Cut', color: '#3949AB', category: 'School' },
  { label: 'Glue', speak: 'Glue', color: '#3949AB', category: 'School' },
  { label: 'Class', speak: 'Class', color: '#3949AB', category: 'School' },
  { label: 'Science', speak: 'Science', color: '#3949AB', category: 'School' },
  { label: 'Math', speak: 'Math', color: '#3949AB', category: 'School' },
  { label: 'Reading', speak: 'Reading', color: '#3949AB', category: 'School' },
  { label: 'Lunch', speak: 'Lunch', color: '#3949AB', category: 'School' },
  { label: 'Recess', speak: 'Recess', color: '#3949AB', category: 'School' },
  { label: 'Backpack', speak: 'Backpack', color: '#3949AB', category: 'School' },
  { label: 'Computer', speak: 'Computer', color: '#3949AB', category: 'School' },

  // Therapy and Health
  { label: 'Exercise', speak: 'Exercise', color: COLOR_SEMANTICS.action, category: 'Therapy' },
  { label: 'Stretch', speak: 'Stretch', color: COLOR_SEMANTICS.action, category: 'Therapy' },
  { label: 'Breathe', speak: 'Breathe', color: COLOR_SEMANTICS.action, category: 'Therapy' },
  { label: 'Massage', speak: 'Massage', color: COLOR_SEMANTICS.action, category: 'Therapy' },
  { label: 'Therapy', speak: 'Therapy', color: COLOR_SEMANTICS.action, category: 'Therapy' },
  { label: 'Rest', speak: 'Rest', color: COLOR_SEMANTICS.action, category: 'Therapy' },
  { label: 'Break', speak: 'Break', color: COLOR_SEMANTICS.action, category: 'Therapy' },
  { label: 'Again', speak: 'Again', color: COLOR_SEMANTICS.action, category: 'Therapy' },
  { label: 'Slow', speak: 'Slow', color: COLOR_SEMANTICS.action, category: 'Therapy' },
  { label: 'Fast', speak: 'Fast', color: COLOR_SEMANTICS.action, category: 'Therapy' },
  { label: 'Gentle', speak: 'Gentle', color: COLOR_SEMANTICS.action, category: 'Therapy' },
  { label: 'Hard', speak: 'Hard', color: COLOR_SEMANTICS.action, category: 'Therapy' },
  { label: 'Strong', speak: 'Strong', color: COLOR_SEMANTICS.action, category: 'Therapy' },
  { label: 'Tired', speak: 'Tired', color: COLOR_SEMANTICS.action, category: 'Therapy' },
  { label: 'Pain', speak: 'Pain', color: COLOR_SEMANTICS.urgent, category: 'Therapy' },
  { label: 'Sick', speak: 'Sick', color: COLOR_SEMANTICS.action, category: 'Therapy' },
  { label: 'Medicine', speak: 'Medicine', color: COLOR_SEMANTICS.action, category: 'Therapy' },
  { label: 'Doctor', speak: 'Doctor', color: COLOR_SEMANTICS.action, category: 'Therapy' },

  // Community & Places
  { label: 'Car', speak: 'Car', color: COLOR_SEMANTICS.object, category: 'Community' },
  { label: 'Drive', speak: 'Drive', color: COLOR_SEMANTICS.object, category: 'Community' },
  { label: 'Go', speak: 'Go', color: COLOR_SEMANTICS.object, category: 'Community' },
  { label: 'Stop', speak: 'Stop', color: COLOR_SEMANTICS.object, category: 'Community' },
  { label: 'Park', speak: 'Park', color: COLOR_SEMANTICS.object, category: 'Community' },
  { label: 'Playground', speak: 'Playground', color: COLOR_SEMANTICS.object, category: 'Community' },
  { label: 'Swing', speak: 'Swing', color: COLOR_SEMANTICS.object, category: 'Community' },
  { label: 'Slide', speak: 'Slide', color: COLOR_SEMANTICS.object, category: 'Community' },
  { label: 'Store', speak: 'Store', color: COLOR_SEMANTICS.object, category: 'Community' },
  { label: 'Shop', speak: 'Shop', color: COLOR_SEMANTICS.object, category: 'Community' },
  { label: 'Library', speak: 'Library', color: COLOR_SEMANTICS.object, category: 'Community' },
  { label: 'Restaurant', speak: 'Restaurant', color: COLOR_SEMANTICS.object, category: 'Community' },
  { label: 'Outside', speak: 'Outside', color: COLOR_SEMANTICS.object, category: 'Community' },
  { label: 'Beach', speak: 'Beach', color: COLOR_SEMANTICS.object, category: 'Community' },
  { label: 'Water', speak: 'Water', color: COLOR_SEMANTICS.object, category: 'Community' },
  { label: 'Bus', speak: 'Bus', color: COLOR_SEMANTICS.object, category: 'Community' },
  { label: 'Train', speak: 'Train', color: COLOR_SEMANTICS.object, category: 'Community' },
  { label: 'Zoo', speak: 'Zoo', color: COLOR_SEMANTICS.object, category: 'Community' },

  // Feelings & Emotions - EXPANDED for emotion-first AAC
  { label: 'Happy', speak: 'Happy', color: '#FDD835', category: 'Feelings' },
  { label: 'Sad', speak: 'Sad', color: '#1E88E5', category: 'Feelings' },
  { label: 'Angry', speak: 'Angry', color: COLOR_SEMANTICS.urgent, category: 'Feelings' },
  { label: 'Scared', speak: 'Scared', color: COLOR_SEMANTICS.feeling, category: 'Feelings' },
  { label: 'Sick', speak: 'Sick', color: '#607D8B', category: 'Feelings' },
  { label: 'Excited', speak: 'Excited', color: '#FDD835', category: 'Feelings' },
  { label: 'Worried', speak: 'Worried', color: '#1E88E5', category: 'Feelings' },
  { label: 'Calm', speak: 'Calm', color: '#43A047', category: 'Feelings' },
  { label: 'Frustrated', speak: 'Frustrated', color: COLOR_SEMANTICS.urgent, category: 'Feelings' },
  { label: 'Annoyed', speak: 'Annoyed', color: '#FF6F00', category: 'Feelings' },
  { label: 'Proud', speak: 'Proud', color: '#FDD835', category: 'Feelings' },
  { label: 'Bored', speak: 'Bored', color: '#757575', category: 'Feelings' },
  { label: 'Surprised', speak: 'Surprised', color: '#8E24AA', category: 'Feelings' },
  { label: 'Nervous', speak: 'Nervous', color: '#1E88E5', category: 'Feelings' },
  { label: 'Lonely', speak: 'Lonely', color: '#1E88E5', category: 'Feelings' },
  { label: 'Confused', speak: 'Confused', color: '#757575', category: 'Feelings' },
  { label: 'Comfortable', speak: 'Comfortable', color: '#43A047', category: 'Feelings' },
  { label: 'Brave', speak: 'Brave', color: '#FDD835', category: 'Feelings' },
  { label: 'Silly', speak: 'Silly', color: '#FDD835', category: 'Feelings' },
  { label: 'Sleepy', speak: 'Sleepy', color: '#546E7A', category: 'Feelings' },
  { label: 'Hungry', speak: 'Hungry', color: '#F57C00', category: 'Feelings' },
  { label: 'Thirsty', speak: 'Thirsty', color: '#00ACC1', category: 'Feelings' },
  { label: 'Hurt', speak: 'Hurt', color: COLOR_SEMANTICS.urgent, category: 'Feelings' },
  { label: 'Itch', speak: 'Itch', color: '#FF6F00', category: 'Feelings' },
  { label: 'Hot', speak: 'Hot', color: '#D32F2F', category: 'Feelings' },
  { label: 'Cold', speak: 'Cold', color: '#0288D1', category: 'Feelings' },
  { label: 'Wonderful', speak: 'Wonderful', color: '#FDD835', category: 'Feelings' },
  { label: 'Loved', speak: 'Loved', color: '#D81B60', category: 'Feelings' },
  { label: 'Special', speak: 'Special', color: '#8E24AA', category: 'Feelings' },
  { label: 'Funny', speak: 'Funny', color: '#FDD835', category: 'Feelings' },

  // Actions & Verbs
  { label: 'Go', speak: 'Go', color: COLOR_SEMANTICS.action, category: 'Actions' },
  { label: 'Stop', speak: 'Stop', color: COLOR_SEMANTICS.action, category: 'Actions' },
  { label: 'Come', speak: 'Come', color: COLOR_SEMANTICS.action, category: 'Actions' },
  { label: 'Look', speak: 'Look', color: COLOR_SEMANTICS.action, category: 'Actions' },
  { label: 'Listen', speak: 'Listen', color: COLOR_SEMANTICS.action, category: 'Actions' },
  { label: 'Open', speak: 'Open', color: COLOR_SEMANTICS.action, category: 'Actions' },
  { label: 'Close', speak: 'Close', color: COLOR_SEMANTICS.action, category: 'Actions' },
  { label: 'Turn on', speak: 'Turn on', color: COLOR_SEMANTICS.action, category: 'Actions' },
  { label: 'Turn off', speak: 'Turn off', color: COLOR_SEMANTICS.action, category: 'Actions' },
  { label: 'Give', speak: 'Give', color: COLOR_SEMANTICS.action, category: 'Actions' },
  { label: 'Take', speak: 'Take', color: COLOR_SEMANTICS.action, category: 'Actions' },
  { label: 'Sit', speak: 'Sit', color: COLOR_SEMANTICS.action, category: 'Actions' },
  { label: 'Stand', speak: 'Stand', color: COLOR_SEMANTICS.action, category: 'Actions' },
  { label: 'Walk', speak: 'Walk', color: COLOR_SEMANTICS.action, category: 'Actions' },
  { label: 'Run', speak: 'Run', color: COLOR_SEMANTICS.action, category: 'Actions' },
  { label: 'Jump', speak: 'Jump', color: COLOR_SEMANTICS.action, category: 'Actions' },
  { label: 'Climb', speak: 'Climb', color: COLOR_SEMANTICS.action, category: 'Actions' },
  { label: 'Push', speak: 'Push', color: COLOR_SEMANTICS.action, category: 'Actions' },
  { label: 'Pull', speak: 'Pull', color: COLOR_SEMANTICS.action, category: 'Actions' },
  { label: 'Hold', speak: 'Hold', color: COLOR_SEMANTICS.action, category: 'Actions' },
  { label: 'Put', speak: 'Put', color: COLOR_SEMANTICS.action, category: 'Actions' },
  { label: 'Pick up', speak: 'Pick up', color: COLOR_SEMANTICS.action, category: 'Actions' },
  { label: 'Drop', speak: 'Drop', color: COLOR_SEMANTICS.action, category: 'Actions' },
  { label: 'Find', speak: 'Find', color: COLOR_SEMANTICS.action, category: 'Actions' },
  { label: 'Get', speak: 'Get', color: COLOR_SEMANTICS.action, category: 'Actions' },
  { label: 'Make', speak: 'Make', color: COLOR_SEMANTICS.action, category: 'Actions' },
  { label: 'Break', speak: 'Break', color: COLOR_SEMANTICS.action, category: 'Actions' },
  { label: 'Fix', speak: 'Fix', color: COLOR_SEMANTICS.action, category: 'Actions' },
  { label: 'Hit', speak: 'Hit', color: COLOR_SEMANTICS.action, category: 'Actions' },
  { label: 'Catch', speak: 'Catch', color: COLOR_SEMANTICS.action, category: 'Actions' },
  { label: 'Throw', speak: 'Throw', color: COLOR_SEMANTICS.action, category: 'Actions' },
  { label: 'Kick', speak: 'Kick', color: COLOR_SEMANTICS.action, category: 'Actions' },
  { label: 'Ask', speak: 'Ask', color: COLOR_SEMANTICS.action, category: 'Actions' },

  // Activities - recreation and structured activities
  { label: 'Play', speak: 'Play', color: '#FF6F00', category: 'Activities' },
  { label: 'Sport', speak: 'Sport', color: '#FF6F00', category: 'Activities' },
  { label: 'Game', speak: 'Game', color: '#FF6F00', category: 'Activities' },
  { label: 'Art', speak: 'Art', color: '#FF6F00', category: 'Activities' },
  { label: 'Movie', speak: 'Movie', color: '#FF6F00', category: 'Activities' },
  { label: 'Music', speak: 'Music', color: '#FF6F00', category: 'Activities' },
  { label: 'Dance', speak: 'Dance', color: '#FF6F00', category: 'Activities' },
  { label: 'Sing', speak: 'Sing', color: '#FF6F00', category: 'Activities' },
  { label: 'Read', speak: 'Read', color: '#FF6F00', category: 'Activities' },
  { label: 'Draw', speak: 'Draw', color: '#FF6F00', category: 'Activities' },
  { label: 'Swim', speak: 'Swim', color: '#FF6F00', category: 'Activities' },
  { label: 'Bike', speak: 'Bike', color: '#FF6F00', category: 'Activities' },
  { label: 'Build', speak: 'Build', color: '#FF6F00', category: 'Activities' },
  { label: 'Watch', speak: 'Watch', color: '#FF6F00', category: 'Activities' },
  { label: 'Listen', speak: 'Listen', color: '#FF6F00', category: 'Activities' },
  { label: 'Learn', speak: 'Learn', color: '#FF6F00', category: 'Activities' },

  // Descriptors - adjectives and descriptive words
  { label: 'Big', speak: 'Big', color: '#00897B', category: 'Descriptors' },
  { label: 'Small', speak: 'Small', color: '#00897B', category: 'Descriptors' },
  { label: 'Good', speak: 'Good', color: '#00897B', category: 'Descriptors' },
  { label: 'Bad', speak: 'Bad', color: '#00897B', category: 'Descriptors' },
  { label: 'Hot', speak: 'Hot', color: '#00897B', category: 'Descriptors' },
  { label: 'Cold', speak: 'Cold', color: '#00897B', category: 'Descriptors' },
  { label: 'Wet', speak: 'Wet', color: '#00897B', category: 'Descriptors' },
  { label: 'Dry', speak: 'Dry', color: '#00897B', category: 'Descriptors' },
  { label: 'Clean', speak: 'Clean', color: '#00897B', category: 'Descriptors' },
  { label: 'Dirty', speak: 'Dirty', color: '#00897B', category: 'Descriptors' },
  { label: 'Soft', speak: 'Soft', color: '#00897B', category: 'Descriptors' },
  { label: 'Hard', speak: 'Hard', color: '#00897B', category: 'Descriptors' },
  { label: 'Smooth', speak: 'Smooth', color: '#00897B', category: 'Descriptors' },
  { label: 'Rough', speak: 'Rough', color: '#00897B', category: 'Descriptors' },
  { label: 'Fast', speak: 'Fast', color: '#00897B', category: 'Descriptors' },
  { label: 'Slow', speak: 'Slow', color: '#00897B', category: 'Descriptors' },
  { label: 'Loud', speak: 'Loud', color: '#00897B', category: 'Descriptors' },
  { label: 'Quiet', speak: 'Quiet', color: '#00897B', category: 'Descriptors' },
  { label: 'Beautiful', speak: 'Beautiful', color: '#00897B', category: 'Descriptors' },
  { label: 'Ugly', speak: 'Ugly', color: '#00897B', category: 'Descriptors' },
  { label: 'Easy', speak: 'Easy', color: '#00897B', category: 'Descriptors' },
  { label: 'Hard', speak: 'Hard', color: '#00897B', category: 'Descriptors' },
  { label: 'Heavy', speak: 'Heavy', color: '#00897B', category: 'Descriptors' },
  { label: 'Light', speak: 'Light', color: '#00897B', category: 'Descriptors' },
  { label: 'Bright', speak: 'Bright', color: '#00897B', category: 'Descriptors' },
  { label: 'Dark', speak: 'Dark', color: '#00897B', category: 'Descriptors' },

  // Places - locations and destinations
  { label: 'Home', speak: 'Home', color: '#00897B', category: 'Places' },
  { label: 'School', speak: 'School', color: '#00897B', category: 'Places' },
  { label: 'Park', speak: 'Park', color: '#00897B', category: 'Places' },
  { label: 'Store', speak: 'Store', color: '#00897B', category: 'Places' },
  { label: 'Hospital', speak: 'Hospital', color: '#00897B', category: 'Places' },
  { label: 'Doctor', speak: 'Doctor', color: '#00897B', category: 'Places' },
  { label: 'Beach', speak: 'Beach', color: '#00897B', category: 'Places' },
  { label: 'Mountain', speak: 'Mountain', color: '#00897B', category: 'Places' },
  { label: 'Forest', speak: 'Forest', color: '#00897B', category: 'Places' },
  { label: 'River', speak: 'River', color: '#00897B', category: 'Places' },
  { label: 'Lake', speak: 'Lake', color: '#00897B', category: 'Places' },
  { label: 'City', speak: 'City', color: '#00897B', category: 'Places' },
  { label: 'Town', speak: 'Town', color: '#00897B', category: 'Places' },
  { label: 'Restaurant', speak: 'Restaurant', color: '#00897B', category: 'Places' },
  { label: 'Library', speak: 'Library', color: '#00897B', category: 'Places' },
  { label: 'Zoo', speak: 'Zoo', color: '#00897B', category: 'Places' },
  { label: 'Playground', speak: 'Playground', color: '#00897B', category: 'Places' },
  { label: 'Street', speak: 'Street', color: '#00897B', category: 'Places' },
  { label: 'Office', speak: 'Office', color: '#00897B', category: 'Places' },
].map(word => ({
  ...word,
  usage_count: 0,
  symbol: getSymbolForWord(word.label),
}));

export const DEFAULT_WORDS: DefaultWord[] = BASE_WORDS;